server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://tobiasdev.ml:8761/eureka/

spring:
  application:
    name: manager-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://tobiasdev.ml:3306/bootex
    username: bootuser
    password: bootuser
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

greeting:
  message: this is dev application.yml


# test message
test.message: "this is a test message: i'm managerService-dev.yml"
